const ListNameBank = [
    "TheSieuRe.com",
    "Techcombank"
    , "BIDV"
    , "Vietinbank"
    , "Agribank"
    , "MoMo"
    , "Vietcombank"
    , "MB Bank"
    , "Sacombank"
    , "VPBank"
    , "ABBank"
    , "ACB Bank"
    , "BAC A BANK"
    , "BaoViet Bank"
    , "DONG A Bank"
    , "EximBank"
    , "HDBank"
    , "MaritimeBank"
    , "PG Bank"
    , "SeABank"
    , "SHB Bank"
    , "TPBank"
    , "VIB Bank"
    , "SAIGON Bank"
    , "PhuongDong OCB"
    , "OCEAN BANK"
    , "LienVietBank"
    , "PVcomBank"
    , "KIENLONGBANK"
    , "NAMABANK"
    , "SCB"
]
const ListKeyNameBank = {
    "TheSieuRe.com": "TheSieuRe.com",
    "Techcombank": 'Techcombank - Ngân hàng Kỹ Thương ViệtNam'
    , "BIDV": "BIDV - Ngân hàng Đầu tư và Phát triển Việt Nam"
    , "Vietinbank": "VietinBank - Ngân hàng TMCP Công thương Việt Nam"
    , "Agribank": "Agribank (hay lỗi) - Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam"
    , "MoMo": "Ví MoMo"
    , "Vietcombank": "Vietcombank - Ngân hàng TMCP Ngoại thương Việt Nam"
    , "MB Bank": "MB Bank - Ngân hàng TMCP quân đội"
    , "Sacombank": "Sacombank - Ngân hàng TMCP Sài Gòn Thương Tín"
    , "VPBank": "VPBank - Ngân hàng TMCP Việt Nam Thịnh Vượng"
    , "ABBank": "ABBank - Ngân hàng TMCP An Bình"
    , "ACB Bank": "ACB Bank - Ngân hàng TMCP Á Châu"
    , "BAC A BANK": "BAC A Bank - Ngân hàng TMCP Bắc Á"
    , "BaoViet Bank": "BaoViet Bank - Ngân Hàng TMCP Bảo Việt"
    , "DONG A Bank": "DONGABank - Ngân hàng TMCP Đông Á"
    , "EximBank": "EximBank - Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam"
    , "HDBank": "HDBank - Ngân hàng TMCP Phát triển Nhà Thành phố Hồ Chí Minh"
    , "MaritimeBank": "MSB Bank (MaritimeBank) - Ngân hàng TMCP Hàng hải Việt Nam"
    , "PG Bank": "PG Bank - Ngân hàng TMCP Xăng dầu Petrolimex"
    , "SeABank": "SeABank - Ngân hàng TMCP Đông Nam Á"
    , "SHB Bank": "SHB - Ngân hàng TMCP Sài Gòn – Hà Nội"
    , "TPBank": "TPBank - Ngân hàng TMCP Tiên Phong"
    , "VIB Bank": "VIB - Ngân hàng Quốc Tế VIB"
    , "SAIGON Bank": "SaiGonBank - Ngân hàng TMCP Sài Gòn Công Thương"
    , "PhuongDong OCB": "OCB - Ngân hàng TMCP Phương Đông"
    , "OCEAN BANK": "OceanBank - Ngân hàng TM TNHH Đại Dương"
    , "LienVietBank": "LienVietBank - Ngân hàng TMCP Bưu điện Liên Việt"
    , "PVcomBank": "PVcomBank - Ngân hàng TMCP Đại chúng Việt Nam"
    , "KIENLONGBANK": "KIENLONGBANK- Ngân Hàng TMCP KIENLONGBANK"
    , "NAMABANK": "NAMABANK-TMCP NAM A"
    , "SCB": "SCB- NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN SÀI GÒN"
}
module.exports = { ListNameBank, ListKeyNameBank }